[package]
name = "piqu/rotai"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"
roact-hooks = "kampfkarren/roact-hooks@0.5.1"
react = "jsdotlua/react@17.0.2"
react-roblox = "jsdotlua/react-roblox@17.0.2"