[package]
name = "piquu/rotai-roact"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rotai = "piquu/rotai@0.1.6"
roact = "roblox/roact@1.4.4"